### ISSUE TITLE
Process crashes on missing parameter

### ISSUE THREAD

**Issue by kaeff** [denouche/node-calibre-api#1]
If I forget to append a required parameter, to, the process crashes and, consequently, the docker container exits. 

From the docker-compose log:
```
calibre_1  | 7 Feb 07:25:06 - POST /calibre/ebook-convert
calibre_1  | /home/nodejs/www/node-calibre-api/app/controllers/CalibreCtrl.js:15
calibre_1  |         var toFormat = fields.to[0];
calibre_1  |                              ^
calibre_1  | TypeError: Cannot read property 'to' of undefined
calibre_1  |     at /home/nodejs/www/node-calibre-api/app/controllers/CalibreCtrl.js:15:30
calibre_1  |     at IncomingMessage.<anonymous> (/home/nodejs/www/node-calibre-api/node_modules/multiparty/index.js:116:9)
calibre_1  |     at IncomingMessage.g (events.js:199:16)
calibre_1  |     at IncomingMessage.emit (events.js:104:17)
calibre_1  |     at _stream_readable.js:908:16
calibre_1  |     at process._tickCallback (node.js:355:11)
readinglist_calibre_1 exited with code 1
```

I'd expect the app to remain running and respond with an accordingly, e.g. 400 Bad Request.

**Comment by denouche** [comment]
Hello,

You're right, this is a mandatory parameter and the app should to crash if it is absent. I note to fix it soon.

By the way, waiting for the fix, the form data  to give is the following:

```
        var formData = {
            file: fs.createReadStream(filePath),
            to: destinationFormat
        }
```
With `destinationFormat` the output file extension wanted, and `file` the file to convert in the multipart form data.

**Comment by kaeff** [comment]
Hi @denouche, thanks for the quick heads up! I was able to use the API from following the readme, all good.

I've noticed a similar error for the `file` parameter by the way. Maybe validating / handling both required params the same way would make sense.
